# Alerting rules for Quenty monitoring
groups:
  - name: quenty.rules
    rules:
      # Application health alerts
      - alert: QuentyAppDown
        expr: up{job="quenty-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Quenty application is down"
          description: "Quenty FastAPI application has been down for more than 1 minute."

      - alert: QuentyHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="quenty-app"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on Quenty app"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes."

      - alert: QuentyHighErrorRate
        expr: rate(http_requests_total{job="quenty-app",status=~"5.."}[5m]) / rate(http_requests_total{job="quenty-app"}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on Quenty app"
          description: "Error rate is {{ $value | humanizePercentage }} for more than 5 minutes."

      # Database alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL high connections"
          description: "PostgreSQL is using {{ $value | humanizePercentage }} of max connections."

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 1 minute."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis is using {{ $value | humanizePercentage }} of available memory."

      # System alerts
      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}% for more than 5 minutes."

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space low"
          description: "Disk space is {{ $value }}% available on {{ $labels.mountpoint }}."